// <auto-generated />
namespace Project.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class defaultValues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(defaultValues));
        
        string IMigrationMetadata.Id
        {
            get { return "202112042125174_defaultValues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
