// <auto-generated />
namespace Project.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class humidityhistorychangedtopublicprops : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(humidityhistorychangedtopublicprops));
        
        string IMigrationMetadata.Id
        {
            get { return "202112031640210_humidity-history-changed-to-public-props"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
